version: '3.9'

services:
  wex.transaction.fb:
    container_name: transactiondb
    hostname: transactiondb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: transactiondb
    volumes:
      - transactiondb_data:/var/lib/postgresql/data
    networks:
      - transaction_network

volumes:
  transactiondb_data:

networks:
  transaction_network:
    driver: bridge