version: '3.9'

services:
  wex.transaction.fb:
    container_name: transactiondb
    hostname: transactiondb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: transactiondb
    volumes:
      - transactiondb_data:/var/lib/postgresql/data
    networks:
      - transaction_network
  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - transaction_network

volumes:
  transactiondb_data:
  redis_data:

networks:
  transaction_network:
    driver: bridge